#!/bin/bash

export TZ=America/Los_Angeles
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export HISTCONTROL="ignoredups,ignoreboth"
export HISTTIMEFORMAT="%s "
export HISTSIZE=1000
shopt -s histappend

# check the window size after each command and, if necessary, 
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s cdspell
set completion-ignore-case on

PS1="\u@\h:\w \$ "
source $HOME/git/home/scripts/git-prompt.sh
# source $HOME/git/home/scripts/ps1.rc

alias reload="source $HOME/.bashrc"
alias sudo="sudo "
export LESS=-Ri

# some more ls aliases

function _tree() {
    \tree -C -I "\.*|*cache*|venv" "${@}" | less -R
}

alias ls='ls -G'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -C'
alias v='vim'
alias t="_tree"

[ -f /etc/bash_completion ] && . /etc/bash_completion

if [[ -d "$HOME/perl5/perlbrew/etc" ]]; then
    source ~/perl5/perlbrew/etc/bashrc
    if [[ -d "$HOME/perl/bin" ]]; then
        perlbrew switch perl-5.14.2
    fi
fi

export VISUAL=$vim
export EDITOR=$vim
export PSQL_EDITOR=$vim

# tmux aliases
alias ta="tmux attach -d -t"
alias tn="cd $HOME; tmux new -s"
alias tl="tmux ls 2>/dev/null || echo 'No sessions available'"

