#!/bin/bash

export TZ=America/Los_Angeles
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary, 
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s cdspell
set completion-ignore-case on

PS1="\u@\h:\w \$ "

alias reload_bashrc="source $HOME/.bashrc"
alias sudo="sudo "
export LESS=-Ri

# some more ls aliases

alias ll='ls -l'
alias la='ls -A'
alias l='ls -C'
alias v='vim'

[ -f /etc/bash_completion ] && . /etc/bash_completion

# tmux aliases
alias ta="tmux attach -d -t"
alias tn="cd $HOME; tmux new -s"
alias tl="tmux ls 2>/dev/null || echo 'No sessions available'"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# custom scripts
script_dir="${HOME}/git/home/scripts"
source "${script_dir}/reset_gemset.rc"
source "${script_dir}/tree_with_color.rc"
source "${script_dir}/custom_history.rc"
alias rg='find $(pwd) -type f -print0 | xargs -0 -P 4 -n 40 grep --color=always -iH'
source "${script_dir}/find_large_directories.rc"

source "${script_dir}/ps1.rc"
source "${HOME}/git/home/dot_files/mcc/rc"

if [ -d "${HOME}/opt/bin" ] ; then 
    export PATH="${HOME}/opt/bin:${PATH}"
fi

vim=$(which vim)
export VISUAL=$vim
export EDITOR=$vim
export PSQL_EDITOR=$vim

