# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew git rvm svn tmux yum history-substring-search)

unsetopt listambiguous

source $ZSH/oh-my-zsh.sh

export PATH="/usr/local/bin:${PATH}"
export PATH="/home/bitcycle/opt/bin:${PATH}"
export PATH="/home/bitcycle/.rvm/gems/ruby-1.9.2-p320/bin:${PATH}"
export PATH="/home/bitcycle/.rvm/gems/ruby-1.9.2-p320@global/bin:${PATH}"
export PATH="/home/bitcycle/.rvm/rubies/ruby-1.9.2-p320/bin:${PATH}"
export PATH="/home/bitcycle/.rvm/bin:${PATH}"
export PATH="/sbin:${PATH}"
export PATH="/bin:${PATH}"
export PATH="/usr/sbin:${PATH}"
export PATH="/usr/bin:${PATH}"
export PATH="/sbin:${PATH}"
export PATH="/usr/sbin:${PATH}"
export PATH="/home/bitcycle/bin:${PATH}"

# export MANPATH="/usr/local/man:$MANPATH"
export EDITOR='vim'

export TZ=America/Los_Angeles
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export LESS=-Ri

alias rg="grep -nrHI" 
alias sudo="sudo "

# ls aliases
export LSCOLORS="exfxcxdxbxegedabagacad"
alias ll='ls -l'
alias la='ls -A'
alias l='ls -C'
alias lh="ls -ld .??*"

# tmux aliases
alias ta="tmux attach -d -t"
alias tn="cd $HOME; tmux new -s"
alias tl="tmux ls 2>/dev/null || echo 'No sessions available'"

# ruby-related aliases
alias rtest="rspec -f d"

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then 
    source "$HOME/.rvm/scripts/rvm"
fi

script_dir=$HOME/git/home/scripts
if [ -d "${script_dir}" ] ; then 
    source "${script_dir}/reset_gemset.rc"
    source "${script_dir}/tree_with_color.rc"
    source "${script_dir}/find_large_directories.rc"
fi

if [ -d "${HOME}/opt/bin" ] ; then 
    export PATH="${HOME}/opt/bin:${PATH}"
fi

# prefer ~/opt/bin/vim, or 
# wherever vim can be found
vim=$(which vim)
export VISUAL=$vim
export EDITOR=$vim
export PSQL_EDITOR=$vim

powerline="$HOME/git/powerline/powerline/bindings/zsh/powerline.zsh"
if [ -f "${powerline}" ] ; then 
    source "${powerline}"
else
    echo "Powerline unavailable at ${powerline}"
fi

if which rvm &>/dev/null ; then 
    mcc_ruby="ruby-1.9.2-p320"
    if rvm list | grep "$mcc_ruby" -q ; then 
        rvm use ruby-1.9.2-p320
    fi
fi

if [ -d ~/git/mcc ] ; then 
    alias pgit="$(find ~/git/mcc -name pgit)"
fi 
